### ISSUE TITLE
Update dependencies !!

### ISSUE THREAD

**Issue by thomaslc66** [istanbuljs/istanbul-lib-processinfo#16]
Please update package.json dependencies !

For exemple uuid is version 7.

**Comment by coreyfarrell** [comment]
This will be done when we're ready, uuid is just released and nothing is wrong with uuid 3.x (note they skipped 4.x, 5.x and 6.x so we're only one version behind).  p-map will not be updated until the next semver-major of istanbuljs modules when we drop node.js 8.

**Comment by quoininc-huudatran** [comment]
`uuid` is now `@8.3.2`, does this change anything regarding the above reason to not update it?

**Comment by shellscape** [comment]
@coreyfarrell please have another look at this. enough time has passed for action.

**Comment by Daghall** [comment]
Maybe time to revisit this issue. The newest major of `uuid` is now 9.

Everytime I install my dependencies I get a deprecation warning, which is annoying and crying wolf. I will uninstall `nyc` and use `npx nyx` instead, as a workaround.
